### ISSUE TITLE
Figure 2.a:  Histogram

### ISSUE THREAD

**Issue by zelenkastiot** [Notebook-Factory/NeuralDecoding_book#1]
**Fig 2.a**: Check with authors if histogram is okay 

Original figure in Python 2.7, matplotlib: 

![image](https://user-images.githubusercontent.com/37374247/85933704-71368080-b8da-11ea-9338-dec9ff57ce9e.png)

(Closest) Reproduced figure with Python 3.6, plotly: 

![image](https://user-images.githubusercontent.com/37374247/85933697-6976dc00-b8da-11ea-8c87-f583a28343c5.png)

Jupyter-book [location]( https://notebook-factory.github.io/NeuralDecoding_book/03/subsection/02-04/sos_notebook2.html
) of figure

Code for original figure located in [RatGPS/2D/results.ipynb](https://github.com/NeuroCSUT/RatGPS/blob/master/2D/results.ipynb)

**Comment by agahkarakuzu** [comment]
@zelenkastiot I think this is a nice start, especially given that our schedule is tight for this one. 

Understanding how 3 types of error proportions change wrt error magnitudes with grouped bars takes a bit more mental energy compared to the overlaid bars. **If the time allows**, you can consider using `bar` object instead of `histogram` to better repeat the original figure.

**Comment by zelenkastiot** [comment]
Thanks @agahkarakuzu ! I will leave it for now. 

Keep you posted
