### ISSUE TITLE
Binder/Docker build is broken

### ISSUE THREAD

**Issue by mathieuboudreau** [Notebook-Factory/NeuralDecoding_book#4]
Test it out here: https://mybinder.org/v2/gh/Notebook-Factory/NeuralDecoding_book/master?urlpath=lab/tree/content%2F03%2Fsubsection%2F01-03%2Fsos_notebook1.ipynb

<img width="1150" alt="Capture d’écran 2020-09-02 à 11 11 20" src="https://user-images.githubusercontent.com/1421029/91994503-0c017000-ed0d-11ea-9703-599c737b6faa.png">

**Comment by zelenkastiot** [comment]
Wierd. I will check it out

**Comment by zelenkastiot** [comment]
Hmm, this is super weird

**Comment by mathieuboudreau** [comment]
I know. @agahkarakuzu

**Comment by mathieuboudreau** [comment]
@TommyBoshkovski

**Comment by zelenkastiot** [comment]
The weird part is I have this repo: https://github.com/zelenkastiot/SoS_binder_py2_py3, with the exact same requirements, postBuild, etc and it is not crashing... Maybe because it is cashed ...

It has something to do with the dependencies probably some update or sth. I am checking it out if I find something I will tag you ... Sad it was working great 💔

**Comment by TommyBoshkovski** [comment]
It was crashing because you were trying to build `jupyterlab-sos` with minification. I would suggest using `--minimize=False` when instaling `jupyterlab-sos` in `postbuild` (see https://github.com/Notebook-Factory/NeuralDecoding_book/commit/278f803a77343d29451aa60915419e36da9938a6).

**Comment by zelenkastiot** [comment]
How you find them so fast?? You really are the king of environments 🤣
